baseURL = 'https://kibaro-fatbn.ondigitalocean.app/'
languageCode = 'en-us'
title = 'Kibaro | Portail sur la Guin√©e'
theme = "book"
enableGitInfo = false

[params]
# BookTheme = 'dark'
# (Optional, default none) Set the path to a logo for the book. If the logo is
# /static/logo.png then the path would be 'logo.png'
# BookLogo = 'logo.png'
BookSection = 'textes'
BookSearch = false
BookComments = false
